{% set name = "pytorch-minimize" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytorch-minimize-{{ version }}.tar.gz
  sha256: 32dfe29759d8c07ca4b740793ec9578e50d1a7c41782e53cff1318d9d9154756

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.18.0
    - scipy >=1.6
    - pytorch >=1.9.0

test:
  imports:
    - torchmin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pytorch-minimize.readthedocs.io
  summary: Newton and Quasi-Newton optimization with PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
